# Generated by Django 6.0 on 2025-12-16 09:18

import employee_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', employee_app.models.CustomUserManager()),
            ],
        ),
    ]
