# Generated by Django 6.0 on 2025-12-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin (HR)'), ('scrum_master', 'Scrum Master'), ('trainer', 'Trainer'), ('employee', 'Employee')], max_length=20),
        ),
    ]
