# Generated by Django 6.0 on 2025-12-18 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_customuser_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=20)),
                ('pan_no', models.CharField(blank=True, max_length=20)),
                ('bank_details', models.TextField(blank=True)),
                ('experience_type', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='biodata/photos/')),
                ('resume', models.FileField(upload_to='biodata/resumes/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='biodata/docs/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='biodata/docs/')),
                ('ssc_school', models.CharField(max_length=255)),
                ('ssc_year', models.PositiveIntegerField()),
                ('ssc_grade', models.CharField(max_length=20)),
                ('ssc_marksheet', models.FileField(upload_to='biodata/docs/')),
                ('sslc_school', models.CharField(max_length=255)),
                ('sslc_year', models.PositiveIntegerField()),
                ('sslc_grade', models.CharField(max_length=20)),
                ('sslc_marksheet', models.FileField(upload_to='biodata/docs/')),
                ('ug_degree', models.CharField(max_length=255)),
                ('ug_institution', models.CharField(max_length=255)),
                ('ug_year', models.PositiveIntegerField()),
                ('ug_documents', models.FileField(upload_to='biodata/docs/')),
                ('pg_degree', models.CharField(blank=True, max_length=255)),
                ('pg_institution', models.CharField(blank=True, max_length=255)),
                ('pg_year', models.PositiveIntegerField(blank=True, null=True)),
                ('pg_documents', models.FileField(blank=True, null=True, upload_to='biodata/docs/')),
                ('cert_course', models.CharField(blank=True, max_length=255)),
                ('cert_institution', models.CharField(blank=True, max_length=255)),
                ('cert_year', models.PositiveIntegerField(blank=True, null=True)),
                ('cert_document', models.FileField(blank=True, null=True, upload_to='biodata/docs/')),
                ('work_experience', models.JSONField(default=list)),
                ('technical_skills', models.TextField()),
                ('soft_skills', models.TextField(blank=True)),
                ('reference_name', models.CharField(blank=True, max_length=255)),
                ('reference_contact', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('doj', models.DateField(blank=True, null=True)),
                ('work_mode', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Email Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
