# Generated by Django 6.0 on 2025-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_biodatarequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodatarequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='biodatarequest',
            name='verification_token',
        ),
        migrations.AlterField(
            model_name='biodatarequest',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='biodatarequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='biodatarequest',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin (HR)'), ('scrum_master', 'Scrum Master'), ('trainer', 'Trainer')], max_length=20),
        ),
    ]
