# Generated by Django 6.0 on 2025-12-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_alter_biodatarequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodatarequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='biodatarequest',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='biodatarequest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='country',
            field=models.CharField(blank=True, choices=[('india', 'India'), ('usa', 'USA'), ('canada', 'Canada'), ('uk', 'UK'), ('australia', 'Australia')], max_length=20),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='first_name',
            field=models.CharField(default='sai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='last_name',
            field=models.CharField(default='bhogadi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='post_applied_for',
            field=models.CharField(blank=True, choices=[('junior_developer', 'Junior Developer'), ('frontend_developer', 'Frontend Developer'), ('full_stack_developer', 'Full Stack Developer'), ('qa_engineer', 'QA Engineer')], max_length=50),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='biodatarequest',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
