# Generated by Django 5.2.9 on 2026-01-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_remove_biodatarequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatarequest',
            name='experience_type',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='biodatarequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='biodatarequest',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20),
        ),
    ]
