# Generated by Django 5.2.9 on 2026-01-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_biodatarequest_user_alter_customuser_role_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='session',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='employeeassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='biodatarequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin (HR)'), ('scrum_master', 'Scrum Master'), ('trainer', 'Trainer')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='EmployeeAssignment',
        ),
    ]
