# Generated by Django 5.2.9 on 2026-01-09 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0011_remove_employeeassignment_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatarequest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_data_request', to=settings.AUTH_USER_MODEL, verbose_name='Linked Employee Account'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin (HR)'), ('scrum_master', 'Scrum Master'), ('trainer', 'Trainer'), ('employee', 'Employee')], max_length=20),
        ),
    ]
