# Generated by Django 5.2.9 on 2026-01-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0013_batch_session_assignment_material_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bio_data_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='employee_app.biodatarequest')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
